# Generated by Django 5.2.4 on 2025-08-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='name_icon',
            field=models.CharField(default='defaultIcon', max_length=100),
        ),
    ]
