# Generated by Django 5.2.4 on 2025-08-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_categoria_name_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name_icon',
            field=models.CharField(default='FaCar', max_length=100),
        ),
    ]
