# Generated by Django 5.2.4 on 2025-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_limitemensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
